#!/usr/bin/env bash
# render_markdown.sh — take a JSON model file path as $1 and emit markdown on stdout.
#
# Input shape:
#   {
#     "repo_name": "...",
#     "generated_at": "ISO-8601",
#     "stats": { "package_count": N, "source_files": N, "lang_breakdown": {"ts":N,"js":N} },
#     "packages": [{"name","dir","lang","file_count","description","entry","external":[...]}, ...],
#     "edges": [{"from","to","count"}, ...],
#     "ownership": ["path1","path2",...],
#     "include_external": true,
#     "regen_cmd": "..."
#   }
#
# Body sections (everything below the header) are deterministic — only the
# header line carrying "generated_at" varies between runs on unchanged input.

set -euo pipefail

if ! command -v python3 >/dev/null 2>&1; then
  echo "render_markdown.sh requires python3" >&2
  exit 2
fi

model_path="${1:?model JSON path required}"

python3 - "$model_path" <<'PY'
import json, sys
m = json.load(open(sys.argv[1]))

out = []
w = out.append

repo = m.get("repo_name") or "(unnamed repo)"
gen  = m.get("generated_at") or ""
stats = m.get("stats") or {}
pkgs = m.get("packages") or []
edges = m.get("edges") or []
ownership = m.get("ownership") or []
include_ext = bool(m.get("include_external"))
regen = m.get("regen_cmd") or "./scripts/codemap.sh"

# --- Header ---------------------------------------------------------------
w(f"# Codemap — {repo}")
w("")
w(f"_Generated: {gen}_  ")
w("_Auto-generated by the `codemap` skill. Regenerate when package boundaries change._")
w("")

lb = stats.get("lang_breakdown") or {}
lb_str = ", ".join(f"{k}={v}" for k,v in sorted(lb.items())) or "n/a"
w("## Summary")
w("")
w(f"- Packages: **{stats.get('package_count', len(pkgs))}**")
w(f"- Source files: **{stats.get('source_files', 0)}**")
w(f"- Language breakdown: {lb_str}")
w("")

# --- Workspace overview ---------------------------------------------------
w("## Workspace overview")
w("")
w("| Package | Path | Lang | Files | Description |")
w("| --- | --- | --- | ---: | --- |")
for p in sorted(pkgs, key=lambda x: x.get("name","")):
    desc = (p.get("description") or "").replace("|", "\\|").replace("\n"," ").strip()
    w(f"| `{p.get('name','')}` | `{p.get('dir','')}` | {p.get('lang','')} | {p.get('file_count',0)} | {desc} |")
w("")

# --- Entry points ---------------------------------------------------------
w("## Entry points")
w("")
for p in sorted(pkgs, key=lambda x: x.get("name","")):
    entry = p.get("entry") or "(none detected)"
    w(f"- `{p.get('name','')}` → `{entry}`")
w("")

# --- Cross-package dependency graph ---------------------------------------
w("## Cross-package dependency graph")
w("")
if not edges:
    w("_No internal package-to-package import edges detected (or static analysis was unavailable)._")
else:
    # Group by source.
    by_from = {}
    for e in edges:
        by_from.setdefault(e["from"], []).append(e)
    w("Directed: `A → B` means package A imports from package B.")
    w("")
    for src in sorted(by_from.keys()):
        targets = sorted(by_from[src], key=lambda e: (-e.get("count",0), e["to"]))
        parts = [f"`{t['to']}` ({t.get('count',0)})" for t in targets]
        w(f"- `{src}` → " + ", ".join(parts))
w("")

# --- External-dep highlights ----------------------------------------------
if include_ext:
    w("## External-dep highlights")
    w("")
    w("Top external dependencies per package, taken from `package.json#dependencies` (not derived from imports).")
    w("")
    any_ext = False
    for p in sorted(pkgs, key=lambda x: x.get("name","")):
        ext = p.get("external") or []
        if not ext: continue
        any_ext = True
        w(f"**`{p.get('name','')}`** — " + ", ".join(f"`{e}`" for e in ext))
    if not any_ext:
        w("_No external dependencies declared in any package.json._")
    w("")

# --- Conventions / ownership ----------------------------------------------
w("## Conventions / ownership")
w("")
if ownership:
    w("Files worth reading for deeper context:")
    w("")
    for path in ownership:
        w(f"- `{path}`")
else:
    w("_No CODEOWNERS / OWNERS / `docs/architecture/*.md` found._")
w("")

# --- Footer ---------------------------------------------------------------
w("---")
w("")
w(f"Regenerate with: `{regen}`")
w("")
w("This file is auto-generated by the `codemap` skill. It captures package boundaries, entry points, and inter-package imports — refresh it when those change, not after routine source edits.")

sys.stdout.write("\n".join(out) + "\n")
PY
